### PR TITLE
dennisme/update rabbitmq stream go client

### PR DESCRIPTION
**Pull request by dennisme**
Fixes issues #301 

Ran
```bash
 go get -u github.com/rabbitmq/rabbitmq-stream-go-client
 go mod vendor
```

Followed by consolidation handleConfirm and handleError per upstream docs https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/README.md#publish-confirmation. 

I removed the `atomic.AddInt32(&totalMessages, 1)` in the handleError func message. Is the intention there to count the error messages? If so happy to put that back. 

CC @dselans :) hey man

### CODE REVIEW

**Comment by dennisme** [comment]
Bah broke the tests 👀

**Review by blinktag — APPROVED** [review]

**Comment by blinktag** [comment]
Awesomesauce, thanks @dennisme!
I don't think the count is necessary anymore, and better to avoid atomic package if it's not really needed

**Comment by dselans** [comment]
Yo @dennisme ! Let's grab beers sometime (if you're still in PDX) - it's been a long time!

**Comment by dennisme** [comment]
@dselans yes sounds great! I'll reach out

**Pull request merged**
